import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/lib/auth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Loader2, Plus, X } from 'lucide-react';

interface VenueFormProps {
  onSuccess?: () => void;
  onCancel?: () => void;
}

export function VenueForm({ onSuccess, onCancel }: VenueFormProps) {
  const { user } = useAuth();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [images, setImages] = useState<string[]>(['']);
  const [amenities, setAmenities] = useState<string[]>(['']);
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    address: '',
    city: '',
    state: '',
    zip_code: '',
    location: '',
    latitude: '',
    longitude: '',
    default_opening_time: '06:00',
    default_closing_time: '22:00',
    contact_email: '',
    contact_phone: '',
  });

  function handleInputChange(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  }

  function handleImageChange(index: number, value: string) {
    const newImages = [...images];
    newImages[index] = value;
    setImages(newImages);
  }

  function addImageField() {
    setImages([...images, '']);
  }

  function removeImageField(index: number) {
    setImages(images.filter((_, i) => i !== index));
  }

  function handleAmenityChange(index: number, value: string) {
    const newAmenities = [...amenities];
    newAmenities[index] = value;
    setAmenities(newAmenities);
  }

  function addAmenityField() {
    setAmenities([...amenities, '']);
  }

  function removeAmenityField(index: number) {
    setAmenities(amenities.filter((_, i) => i !== index));
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    
    if (!user) {
      toast({
        title: 'Error',
        description: 'You must be logged in to create a venue',
        variant: 'destructive',
      });
      return;
    }

    setLoading(true);

    try {
      const filteredImages = images.filter(img => img.trim() !== '');
      const filteredAmenities = amenities.filter(am => am.trim() !== '');

      const { error } = await supabase.from('venues').insert({
        owner_id: user.id,
        name: formData.name,
        description: formData.description || null,
        address: formData.address,
        city: formData.city,
        state: formData.state,
        zip_code: formData.zip_code,
        location: formData.location,
        latitude: formData.latitude ? parseFloat(formData.latitude) : null,
        longitude: formData.longitude ? parseFloat(formData.longitude) : null,
        images: filteredImages.length > 0 ? filteredImages : [],
        amenities: filteredAmenities.length > 0 ? filteredAmenities : [],
        default_opening_time: formData.default_opening_time,
        default_closing_time: formData.default_closing_time,
        contact_email: formData.contact_email || null,
        contact_phone: formData.contact_phone || null,
        status: 'pending',
        slug: '', // Will be auto-generated by trigger
      } as any);

      if (error) throw error;

      toast({
        title: 'Success',
        description: 'Venue submitted for approval',
      });

      onSuccess?.();
    } catch (error: any) {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Create New Venue</CardTitle>
        <CardDescription>Add a sports venue to manage multiple courts</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <Label htmlFor="name">Venue Name *</Label>
              <Input
                id="name"
                name="name"
                required
                value={formData.name}
                onChange={handleInputChange}
                placeholder="e.g., Sports Arena"
              />
            </div>
            <div>
              <Label htmlFor="location">Display Name *</Label>
              <Input
                id="location"
                name="location"
                required
                value={formData.location}
                onChange={handleInputChange}
                placeholder="e.g., Downtown Sports Complex"
              />
            </div>
          </div>

          <div>
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              name="description"
              value={formData.description}
              onChange={handleInputChange}
              placeholder="Describe your venue..."
              rows={3}
            />
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <Label htmlFor="address">Address *</Label>
              <Input
                id="address"
                name="address"
                required
                value={formData.address}
                onChange={handleInputChange}
                placeholder="Street address"
              />
            </div>
            <div>
              <Label htmlFor="city">City *</Label>
              <Input
                id="city"
                name="city"
                required
                value={formData.city}
                onChange={handleInputChange}
                placeholder="City"
              />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <Label htmlFor="state">State *</Label>
              <Input
                id="state"
                name="state"
                required
                value={formData.state}
                onChange={handleInputChange}
                placeholder="State"
              />
            </div>
            <div>
              <Label htmlFor="zip_code">Zip Code *</Label>
              <Input
                id="zip_code"
                name="zip_code"
                required
                value={formData.zip_code}
                onChange={handleInputChange}
                placeholder="12345"
              />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <Label htmlFor="latitude">Latitude (Optional)</Label>
              <Input
                id="latitude"
                name="latitude"
                type="number"
                step="any"
                value={formData.latitude}
                onChange={handleInputChange}
                placeholder="40.7128"
              />
            </div>
            <div>
              <Label htmlFor="longitude">Longitude (Optional)</Label>
              <Input
                id="longitude"
                name="longitude"
                type="number"
                step="any"
                value={formData.longitude}
                onChange={handleInputChange}
                placeholder="-74.0060"
              />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <Label htmlFor="default_opening_time">Default Opening Time</Label>
              <Input
                id="default_opening_time"
                name="default_opening_time"
                type="time"
                value={formData.default_opening_time}
                onChange={handleInputChange}
              />
            </div>
            <div>
              <Label htmlFor="default_closing_time">Default Closing Time</Label>
              <Input
                id="default_closing_time"
                name="default_closing_time"
                type="time"
                value={formData.default_closing_time}
                onChange={handleInputChange}
              />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <Label htmlFor="contact_email">Contact Email (Optional)</Label>
              <Input
                id="contact_email"
                name="contact_email"
                type="email"
                value={formData.contact_email}
                onChange={handleInputChange}
                placeholder="contact@venue.com"
              />
            </div>
            <div>
              <Label htmlFor="contact_phone">Contact Phone (Optional)</Label>
              <Input
                id="contact_phone"
                name="contact_phone"
                value={formData.contact_phone}
                onChange={handleInputChange}
                placeholder="+1234567890"
              />
            </div>
          </div>

          <div>
            <Label>Venue Images</Label>
            <div className="space-y-2 mt-2">
              {images.map((img, index) => (
                <div key={index} className="flex gap-2">
                  <Input
                    value={img}
                    onChange={(e) => handleImageChange(index, e.target.value)}
                    placeholder="https://example.com/image.jpg"
                  />
                  {images.length > 1 && (
                    <Button
                      type="button"
                      variant="outline"
                      size="icon"
                      onClick={() => removeImageField(index)}
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              ))}
              <Button type="button" variant="outline" size="sm" onClick={addImageField}>
                <Plus className="h-4 w-4 mr-1" />
                Add Image
              </Button>
            </div>
          </div>

          <div>
            <Label>Venue Amenities</Label>
            <div className="space-y-2 mt-2">
              {amenities.map((amenity, index) => (
                <div key={index} className="flex gap-2">
                  <Input
                    value={amenity}
                    onChange={(e) => handleAmenityChange(index, e.target.value)}
                    placeholder="e.g., Parking, Cafeteria, Lockers"
                  />
                  {amenities.length > 1 && (
                    <Button
                      type="button"
                      variant="outline"
                      size="icon"
                      onClick={() => removeAmenityField(index)}
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              ))}
              <Button type="button" variant="outline" size="sm" onClick={addAmenityField}>
                <Plus className="h-4 w-4 mr-1" />
                Add Amenity
              </Button>
            </div>
          </div>

          <div className="flex gap-2">
            {onCancel && (
              <Button type="button" variant="outline" onClick={onCancel} className="flex-1">
                Cancel
              </Button>
            )}
            <Button type="submit" disabled={loading} className={onCancel ? "flex-1" : "w-full"}>
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Submitting...
                </>
              ) : (
                'Submit for Approval'
              )}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
